### ISSUE TITLE
beadsynt example

### ISSUE THREAD

**Issue by tjingboem** [csound-plugins/csound-plugins#10]
My goal is to analyze and save a wav file, giving it the extension **.mtx**, with loristrck_pack, and then then in Csound using beadsynt to read this mtx file again.
I read in the documentation for loristrck_pack:
_This is mostly thought to be used in tandem with csound's beadsynt opcode, which performs band-enhanced-additive-synthesis in realtime_

In the manual/examples folder of the Csound manual i found the **fox.mtx**

I tried running the example from the beadsynt documentation https://csound-plugins.github.io/csound-plugins/opcodes/beadsynt.html
but get an error:
```
INIT ERROR in instr 1 (opcode beadsynt) line 63: bandwidths array is too small
 from file /media/menno/datae/onderzoek/manualExamples/beadsynthNEW.csd (1),aout	beadsynt	kF	kA	kB	-1	iflags	ifreqscale	1	-1	-1	
		   T  0.000 - note deleted.  i1 had 1 init errors
```
Not yet being familiar with beadsynt, can you please check if the example still works for you?

**Comment by gesellkammer** [comment]
Try the one here:

https://github.com/csound-plugins/csound-plugins/blob/master/src/beosc/examples/fox.mtx

**Comment by tjingboem** [comment]
Yes, that one works. This _fox.mtx_ is 2 x bigger in size than the one that is present in the examples folder of the Csound manual. I will remove that one from the repo to avoid further confusion.

And i was able to create a new mtx file with loristrck_pack!
```
menno@mennoASUSZ170 ~ $ loristrck_pack MathewsN.wav
Using dt = 1.30 ms
MathewsN.mtx

```
This is a good starting point, thanks for your help.

**Comment by tjingboem** [comment]
i have yet another question on the information i have on the **beadsynt** opcode.
It is about how to understand the flags.

```
iflags | Description
-- | --
+1 | Uniform noise / Gaussian noise
+2 | Fast (no interpolation) oscillator / Linear interpolation
+4 | No frequency interpolation / Frequency interpolation
```
i am not sure, for example, if '1' is or the uniform or the gaussian noise?
And does '2' mean 'no interpolation' or 'linear interpolation'?

The list i have gathered now looks like this:
![Screenshot from 2022-08-29 20-25-54](https://user-images.githubusercontent.com/6670911/187274191-b465e6ab-1352-46bb-878d-8db62e8cdaa4.png)

**Comment by gesellkammer** [comment]
These are binary flags, so without any flags (0) it is the cheapest possible: uniform noise, fast oscillator, no frequency interpolation.

+1 changes the noise type to gaussian, which sounds more natural (this used to be a very expensive option but I came up with a very ood optimization so at the moment  gaussian noise is  almost as cheap as uniform).

+2 sets linear interpolation for the sine oscillators,

+4 interpolates frequencies at audio level.

NB: Amplitudes are always linearly interpolated as audio level

**Comment by tjingboem** [comment]
Thanks for clearing that up!

I now have 2 instruments: one that is using **loristrck_pack** with no further arguments (produces a mtx file), after a few seconds the second instrument using **beadsynt** for playback.

This way, i analyzed the _fox_ and play it back later. But i get a very different sounding result from your _fox.mtx_.

I have read that **loristrck_analyze** can be used before **loristrck_pack** for more control in the analysis stage. Is this combination needed to get the _fox.mtx_ file that you produced?
What are the arguments?
.
my fox:
[fox.mtx.zip](https://github.com/csound-plugins/csound-plugins/files/9451164/fox.mtx.zip)

**Comment by gesellkammer** [comment]
loristrck_analyze --help

For any further inquiries, please consider reading the documentation first:

https://loristrck.readthedocs.io (https://loristrck.readthedocs.io/en/latest/commandline.html)

**Comment by tjingboem** [comment]
I have printed out these documents a week ago and going through them the best i can.
But i won't bother you again- which is a pity as i think your opcodes and other work are interesting.
