### ISSUE TITLE
beadsynt segmentation violation

### ISSUE THREAD

**Issue by enchilada404** [csound-plugins/csound-plugins#11]
CSound version **6.18.1**
risset version **2.1.0**
beosc version **1.14.1**

Windows 10 and Windows 11

The beadsynt.csd example now generates this output:

```
PS C:\Users\falkd\Desktop\csdresynt> csound beadsynt.csd
UnifiedCSD:  beadsynt.csd
rtaudio: PortAudio module enabled ...
using callback interface
rtmidi: PortMIDI module enabled
Elapsed time at end of orchestra compile: real: 0.044s, CPU: 0.044s
sorting score ...
        ... done
Elapsed time at end of score sort: real: 0.045s, CPU: 0.045s
--Csound version 6.18 (double samples) Nov 23 2022
[commit: a1580f9cdf331c35dceb486f4231871ce0b00266]
libsndfile-1.1.0
graphics suppressed, ascii substituted
sr = 44100.0, kr = 344.531, ksmps = 128
0dBFS level = 1.0, A4 tuning = 440.0
ftable 101:
deferred alloc for fox.mtx
audio sr = 44100, monaural
opening WAV infile fox.mtx
  defer length 318315
ftable 101:     318315 points, scalemax 20268.840
          _
                            -


                     '                                              -
                 _ _                 _     -    '          _
        .              _      _                          .   '        .        -
_._-________-___________________-________-__________-___________________.____'__
orch now loaded
audio buffered in 4096 sample-frame blocks
PortAudio V19.7.0-devel, revision unknown
   0: dac0 (Microsoft Sound Mapper - Output [MME, 0 in, 2 out])
   1: dac1 (Speakers/Headphones (Intel SST  [MME, 0 in, 2 out])
   2: dac2 (SMT27A550 (Intel SST Audio Devi [MME, 0 in, 2 out])
   4: dac4 (Speakers/Headphones (Intel SST Audio Device (WDM)) [Windows DirectSound, 0 in, 2 out])
   5: dac5 (SMT27A550 (Intel SST Audio Device (WDM)) [Windows DirectSound, 0 in, 2 out])
   6: dac6 (ReaRoute ASIO (x64) [ASIO, 16 in, 16 out])
   7: dac7 (Speakers/Headphones (Intel SST Audio Device (WDM)) [Windows WASAPI, 0 in, 2 out])
   8: dac8 (SMT27A550 (Intel SST Audio Device (WDM)) [Windows WASAPI, 0 in, 2 out])
   9: dac9 (Output (IntelSST Audio Wave for Hdmi) [Windows WDM-KS, 0 in, 2 out])
  10: dac10 (Speakers (IntelSST Audio Wave for IHF) [Windows WDM-KS, 0 in, 2 out])
PortAudio: selected output device 'Speakers/Headphones (Intel SST '
writing 8192 sample blks of 64-bit floats to dac
SECTION 1:
new alloc for instr 1:

csound command: Segmentation violation
```
After this, CSound quits without playing any sound.

**Comment by gesellkammer** [comment]
Thanks for the report. I can confirm the same crash on linux. I will investigate it as soon as I can

**Comment by gesellkammer** [comment]
Could you try the latest build?

https://github.com/csound-plugins/csound-plugins/releases/tag/latest

Just place the beosc.dll into your plugins64 folder

**Comment by enchilada404** [comment]
Ok, with the new build there is some sound output... but it sounds like it has been "frequency-time-stretched", and then it ends in ```csound command: Segmentation violation``` again.

**Comment by enchilada404** [comment]
I just tried **v1.15.0** and the **Development Build**, but there's no change in behavior here. Sound is warped and then back to ```csound command: Segmentation violation```.

Also, when I check versions with risset, it still lists versions 1.14.1 of all plugins.

**Comment by enchilada404** [comment]
Here's just to let you know that **v1.17.0** from **Apr 20** is still giving the same result.
I think that the loristrck/beadsynt combination is pretty unique, and it would be nice to have it working again.
Let me know if I can help in any way.

**Comment by gesellkammer** [comment]
Could you try the latest Develoment build?

**Comment by gesellkammer** [comment]
With the github actions tests I can confirm that this is now fixed

**Comment by enchilada404** [comment]
Sorry to say, both the **latest development build** and **1.18.0** also fails with the same segmentation violation here on win 10. Sound has some phase issues and plays back at wrong speed and pitch.

**Comment by gesellkammer** [comment]
I can confirm that it is building and running correctly in windows latest (this corresponds to windows server 2022) with last released csound 6.18. This renders cleanly without any errors.

**Comment by gesellkammer** [comment]
I can confirm that it is building and running correctly in windows latest (this corresponds to windows server 2022) with last released csound 6.18. This renders cleanly without any errors.

**Comment by enchilada404** [comment]
For me it will render to file (non-realtime) without reporting any errors.
However, it sounds like this (the default "fox" example): 

https://github.com/csound-plugins/csound-plugins/assets/60402643/decff3c7-cd57-4f81-a32b-de0d30ae8ca3

...and realtime gives me segmentation violation on both win 10 & 11, with sound being identical with above non-realtime output.

**Comment by gesellkammer** [comment]
This is how the example is supposed to sound, see the csd regarding speed and filtering. Regarding segmentation fault with realtime, that I cannot confirm.

**Comment by enchilada404** [comment]
oops my mistake. I thought I was using my version that just plays the sound unmodified, sorry.
Still getting segmentation fault though when playing beadsynt.csd example 🤔
Otherwise it seems to work fine.

**Comment by gesellkammer** [comment]
If it renders to file but not to dac then your segmentation fault has probably little to do with the opcode itself. From the point of view of the opcode there is no difference.

**Comment by enchilada404** [comment]
It renders to dac, and now it sounds correct.
Segmentation violation comes after Csound is finished.
