### ISSUE TITLE
building on Windows...

### ISSUE THREAD

**Issue by rorywalsh** [csound-plugins/csound-plugins#3]
Just tried to do a quick build here on Windows, I have nasm installed. It throws the following build errors:

1>------ Build started: Project: else, Configuration: Debug x64 ------
2>------ Build started: Project: klib, Configuration: Debug x64 ------
3>------ Build started: Project: poly, Configuration: Debug x64 ------
4>------ Build started: Project: sched, Configuration: Debug x64 ------
5>------ Build started: Project: jsusfx_csound_project, Configuration: Debug x64 ------
1>Microsoft (R) C/C++ Optimizing Compiler Version 19.13.26132 for x64
1>Copyright (C) Microsoft Corporation.  All rights reserved.
1>
3>Microsoft (R) C/C++ Optimizing Compiler Version 19.13.26132 for x64
4>Microsoft (R) C/C++ Optimizing Compiler Version 19.13.26132 for x64
4>Copyright (C) Microsoft Corporation.  All rights reserved.
4>
1>cl /c /I"C:\Program Files\Csound6_x64\include\csound" /I"C:\Users\rory\sourcecode\vcpkg\installed\x64-windows\include" /Zi /Wall /WX- /diagnostics:classic /Od /Ob0 /D WIN32 /D _WINDOWS /D USE_DOUBLE /D B64BIT /D "CMAKE_INTDIR=\"Debug\"" /D else_EXPORTS /D _WINDLL /D _MBCS /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"else.dir\Debug\\" /Fd"else.dir\Debug\vc141.pdb" /Gd /TC /errorReport:prompt  /W3";"-std=c99 -fPIC "C:\Users\rory\sourcecode\csound-plugins\src\else\src\else.c"
1>cl : Command line error D8021: invalid numeric argument '/W3;-std=c99'
1>Done building project "else.vcxproj" -- FAILED.
3>Copyright (C) Microsoft Corporation.  All rights reserved.
3>
3>cl /c /I"C:\Program Files\Csound6_x64\include\csound" /I"C:\Users\rory\sourcecode\vcpkg\installed\x64-windows\include" /Zi /Wall /WX- /diagnostics:classic /Od /Ob0 /D WIN32 /D _WINDOWS /D USE_DOUBLE /D B64BIT /D "CMAKE_INTDIR=\"Debug\"" /D poly_EXPORTS /D _WINDLL /D _MBCS /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"poly.dir\Debug\\" /Fd"poly.dir\Debug\vc141.pdb" /Gd /TC /errorReport:prompt  /W3";"-std=c99 -fPIC "C:\Users\rory\sourcecode\csound-plugins\src\poly\src\poly.c"
3>cl : Command line error D8021: invalid numeric argument '/W3;-std=c99'
3>Done building project "poly.vcxproj" -- FAILED.
4>cl /c /I"C:\Program Files\Csound6_x64\include\csound" /I"C:\Users\rory\sourcecode\vcpkg\installed\x64-windows\include" /Zi /Wall /WX- /diagnostics:classic /Od /Ob0 /D WIN32 /D _WINDOWS /D USE_DOUBLE /D B64BIT /D "CMAKE_INTDIR=\"Debug\"" /D sched_EXPORTS /D _WINDLL /D _MBCS /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"sched.dir\Debug\\" /Fd"sched.dir\Debug\vc141.pdb" /Gd /TC /errorReport:prompt  /W3";"-std=c99 -fPIC "C:\Users\rory\sourcecode\csound-plugins\src\sched\src\sched.c"
4>cl : Command line error D8021: invalid numeric argument '/W3;-std=c99'
4>Done building project "sched.vcxproj" -- FAILED.
2>Microsoft (R) C/C++ Optimizing Compiler Version 19.13.26132 for x64
2>Copyright (C) Microsoft Corporation.  All rights reserved.
2>
2>cl /c /I"C:\Program Files\Csound6_x64\include\csound" /I"C:\Users\rory\sourcecode\vcpkg\installed\x64-windows\include" /Zi /Wall /WX- /diagnostics:classic /Od /Ob0 /D WIN32 /D _WINDOWS /D USE_DOUBLE /D B64BIT /D "CMAKE_INTDIR=\"Debug\"" /D klib_EXPORTS /D _WINDLL /D _MBCS /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"klib.dir\Debug\\" /Fd"klib.dir\Debug\vc141.pdb" /Gd /TC /errorReport:prompt  /W3";"-std=c99 -fPIC "C:\Users\rory\sourcecode\csound-plugins\src\klib\src\klib.c"
2>cl : Command line error D8021: invalid numeric argument '/W3;-std=c99'
2>Done building project "klib.vcxproj" -- FAILED.
5>Microsoft (R) C/C++ Optimizing Compiler Version 19.13.26132 for x64
5>Copyright (C) Microsoft Corporation.  All rights reserved.
5>
5>cl /c /I"C:\Users\rory\sourcecode\csound-plugins\src\jsusfx\jsfx-src" /I"C:\Program Files\Csound6_x64\include\csound" /I"C:\Users\rory\sourcecode\vcpkg\installed\x64-windows\include" /Zi /W3 /WX- /diagnostics:classic /Od /Ob0 /D WIN32 /D _WINDOWS /D WDL_FFT_REALSIZE=8 /D "CMAKE_INTDIR=\"Debug\"" /D jsusfx_csound_project_EXPORTS /D _WINDLL /D _MBCS /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"jsusfx_csound_project.dir\Debug\\" /Fd"jsusfx_csound_project.dir\Debug\vc141.pdb" /Gd /TP /wd4091 /wd4996 /errorReport:prompt  /EHsc";"-std=c++11 "C:\Users\rory\sourcecode\csound-plugins\src\jsusfx\csound\jsusfx_csound.cpp"
5>
5>cl : Command line warning D9002: ignoring unknown option '/EH;'
5>cl : Command line warning D9002: ignoring unknown option '/EH-'
5>cl : Command line warning D9002: ignoring unknown option '/EHt'
5>cl : Command line warning D9002: ignoring unknown option '/EHd'
5>cl : Command line warning D9002: ignoring unknown option '/EH='
5>cl : Command line warning D9002: ignoring unknown option '/EH+'
5>cl : Command line warning D9002: ignoring unknown option '/EH+'
5>cl : Command line warning D9002: ignoring unknown option '/EH1'
5>cl : Command line warning D9002: ignoring unknown option '/EH1'
5>jsusfx_csound.cpp
5>C:\Users\rory\sourcecode\csound-plugins\src\jsusfx\jsfx-src\jsusfx.h(97): warning C4244: 'return': conversion from 'EEL_F' to 'float', possible loss of data
5>C:\Users\rory\sourcecode\csound-plugins\src\jsusfx\csound\jsusfx_csound.cpp(198): warning C4244: '=': conversion from 'EEL_F' to 'uint8_t', possible loss of data
5>C:\Users\rory\sourcecode\csound-plugins\src\jsusfx\csound\jsusfx_csound.cpp(200): warning C4244: '=': conversion from 'EEL_F' to 'uint8_t', possible loss of data
5>C:\Users\rory\sourcecode\csound-plugins\src\jsusfx\csound\jsusfx_csound.cpp(201): warning C4244: '=': conversion from 'EEL_F' to 'uint8_t', possible loss of data
5>C:\Users\rory\sourcecode\csound-plugins\src\jsusfx\csound\jsusfx_csound.cpp(203): warning C4244: 'initializing': conversion from 'EEL_F' to 'int', possible loss of data
5>C:\Users\rory\sourcecode\csound-plugins\src\jsusfx\csound\jsusfx_csound.cpp(1242): warning C4003: not enough actual parameters for macro 'min'
5>C:\Users\rory\sourcecode\csound-plugins\src\jsusfx\csound\jsusfx_csound.cpp(1242): error C2589: '(': illegal token on right side of '::'
5>C:\Users\rory\sourcecode\csound-plugins\src\jsusfx\csound\jsusfx_csound.cpp(1242): error C2062: type 'unknown-type' unexpected
5>C:\Users\rory\sourcecode\csound-plugins\src\jsusfx\csound\jsusfx_csound.cpp(1242): error C2059: syntax error: ')'
5>C:\Users\rory\sourcecode\csound-plugins\src\jsusfx\csound\jsusfx_csound.cpp(1396): warning C4003: not enough actual parameters for macro 'min'
5>C:\Users\rory\sourcecode\csound-plugins\src\jsusfx\csound\jsusfx_csound.cpp(1396): error C2589: '(': illegal token on right side of '::'
5>C:\Users\rory\sourcecode\csound-plugins\src\jsusfx\csound\jsusfx_csound.cpp(1396): error C2062: type 'unknown-type' unexpected
5>C:\Users\rory\sourcecode\csound-plugins\src\jsusfx\csound\jsusfx_csound.cpp(1396): error C2059: syntax error: ')'
5>Done building project "jsusfx_csound_project.vcxproj" -- FAILED.
6>------ Skipped Build: Project: INSTALL, Configuration: Debug x64 ------
6>Project not selected to build for this solution configuration 
========== Build: 0 succeeded, 5 failed, 3 up-to-date, 1 skipped ==========

[edit] I'm reluctant to modify the Visual Studio projects to fix these, they should probably be addressed in the cmake config right? 

[edit] the source file compile error relating to std::numeric_limits can be fixed by wrapping the call in parenthesis. I'm not sure how to address the command line compiler parameters..

**Comment by rorywalsh** [comment]
I've fixed most of the problem, but I can't get past the build errors with the jsusfx project. I can make a PR for the rest of the stuff, but maybe you prefer to look into it yourself?

**Comment by gesellkammer** [comment]
I replied to this via email, but evidently it did not get through. I will look into this as soon as I can, thanks for the help.
