### ISSUE TITLE
Feature request: that poly0 could work with opcodes with indefinite number of arguments

### ISSUE THREAD

**Issue by andreasbergsland** [csound-plugins/csound-plugins#4]
Hi
I would like that poly0 (and poly if the same goes for that) would work with opcodes with an indefinite number of arguments, such as the schedule and event family of opcodes.
Best, Andreas Bergsland

**Comment by gesellkammer** [comment]
This is solved by commit cca10776824e63834487c7582a7b143ab06811d4

**Comment by gesellkammer** [comment]
now (hopefully) really fixed via f16e14ecd7852299eeefeb5fe08483d10c3f8d5d
