### ISSUE TITLE
small issue, but

### ISSUE THREAD

**Issue by tjingboem** [csound-plugins/csound-plugins#5]
nevertheless i just file them:

i run the example for the defer opcode, and the printing in the output console is a bit messy here (Linux)
This can be more readable when:
  prints "Instr 1 started\n"
  defer "prints", "Instr 1 stopped after %.3f seconds\n", kt

**Comment by gesellkammer** [comment]
Thanks for the issue. Could you please make a PR? The file to modify is: https://github.com/csound-plugins/csound-plugins/blob/master/src/else/docs/defer.md

**Comment by tjingboem** [comment]
I will do a PR- but have never worked with it. I hope this is a change of learning how all this is done.
What should i do once i change something? How do i let you know?

**Comment by tjingboem** [comment]
i think i have done it
