### ISSUE TITLE
Usage of hdf5read crashes the instrument at compile time

### ISSUE THREAD

**Issue by idranoels** [csound-plugins/csound-plugins#9]
Hello everybody
I’m using Cabbage as a frontend for CSound and I’m trying to user hdf5write/hdf5read to save and restore datas to disk.
In a test file I have a line like this:

```
printks"before hdf5read:\n", 0
;        aArray[], aVar, kVar hdf5read "f:/mypath/src/cabbage/example.h5", "aArray*", "aVar", "kVar" ; Open hdf5 file and read variables
printks"after hdf5read:\n", 0

```
but if I remove the comment Cabbage suddenly crashes without printing anything before, so it should be a compile time issue.
The same issue occurs when I use CSound standalone.

I’m running under the following SW stack:

```
Windows 10
CSound 6.16 (double samples) Jul 17 2021
Cabbage 2.8.0

```
I attach:

    CSound instrument [test_3.csd.txt](https://github.com/csound-plugins/csound-plugins/files/7958211/test_3.csd.txt)
    CSound output [test_3.txt](https://github.com/csound-plugins/csound-plugins/files/7958212/test_3.txt)
    Windows Event Viewer crash [EventViewer.txt](https://github.com/csound-plugins/csound-plugins/files/7958213/EventViewer.txt)

Thank you in advance

Sergio

**Comment by gesellkammer** [comment]
This is the repository for the external plugins defined here: https://csound-plugins.github.io/csound-plugins/
The opcodes you mention are part of csound's own plugins, which live here: https://github.com/csound/plugins
